version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    restart: unless-stopped
    ports:
      - "34723:34723"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookdb
      - JWT_SECRET=supersecret
    depends_on:
      - mongo

volumes:
  mongo-data:
